### ISSUE TITLE
Implicit or Explicit Assumption of <ACain> User Profile in Some File Paths

### ISSUE THREAD

**Issue by njsch** [splashkit/splashkit-core#128]
@macite, One other student and I have found a weird phenomenon sometimes occurring where Splashkit sometimes looks for files within a user profile called "ACain", which I can only assume to be Andrew's computer.  It's happening in my 7.4D Custom Program assessment for SIT102, where I can neither create, nor open, a database because splashkit::database thinks I am Andrew and not Nathaniel.  How is this possible?

It's looking for ```C:/Users/acain/Documents/Code/splashkit/coresdk/src/coresdk/database.cpp```

This is not strictly a compilation error.  This occurs after I run my program and attempt to create a database.

It's looking for a source file that doesn't exist, from a location that doesn't exist.  It's having trouble with an alleged line of code from 252 of database.cpp.

**Comment by macite** [comment]
This is a logging message from the library code - which was compiled from this location. The line is "LOG(WARNING) << "Failed to open database " + file_path;"

Which should have been "LOG(WARNING) << "Failed to open database " << file_path;" so when this crashed it reported this with the symbols from the library that indicate where the source code is for this crash location.

In this case the problem is that it cannot open your database file. It may be worth checking you have the necessary database folder in resources as it should create the file if it is not there.

Hope that helps.
